apiVersion: argoproj.io/v1alpha1
kind: `ApplicationSet`
metadata:
  name: guestbook-allclusters-app-set
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: ocm-placement-generator
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: aws-app-placement
      requeueAfterSeconds: 30
  template:
    metadata:
      annotations:
#        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
#        argocd.argoproj.io/skip-reconcile: "true" 
      labels:
#        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true" 
      name: spring-petclinic-appset-{{name}}
    spec:
      destination:
        namespace: spring-petclinic
#        server: https://kubernetes.default.svc
        server: "{{server}}"
      project: default
      source:
        path: app 
        repoURL: https://github.com/siamaksade/openshift-gitops-getting-started
        targetRevision: HEAD
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
